### ISSUE TITLE
C++支持问题

### ISSUE THREAD

**Issue by alittlehorse** [redguardtoo/vscode-matchit#4]
您好陈斌，非常感谢您的插件，这个插件对typescript有很好的支持，帮助我简化了操作，给予了很大的帮助。
查看Readme时，发现本插件提供了对C++的支持。但在实际操作时，发现并不如对typescript的支持，请看下图
![c++支持](https://user-images.githubusercontent.com/26022056/79408373-baf71680-7fcd-11ea-93a1-80cfe7bfac05.gif)

**Comment by redguardtoo** [comment]
目前matchit只是把利用了vscode的两个API。所以不会超出vscode默认提供的功能。

**Comment by alittlehorse** [comment]
谢谢！
